{
 "title": "AWS Cost Dashboard Example v2",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 1 },
   "options": {
    "content": "<img src=\"https://upload.wikimedia.org/wikipedia/commons/9/93/Amazon_Web_Services_Logo.svg\" style=\"background-color: white; width: 100%; padding: 10px; margin-bottom: 20px;\">\n<h4>AWS Cost Overview</h4>\n<p>This dashboard summarizes your costs of AWS products.</p>"
   }
  },
  {
   "title": "AWS Total Costs",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (max_over_time(aws_cost[24h] offset -24h))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Costs per AWS Account",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (Publisher) (max_over_time(aws_cost[24h] offset -24h))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Costs per AWS Region",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (RegionName) (max_over_time(aws_cost[24h] offset -24h))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Costs per Project",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (ProjectName) (max_over_time(aws_cost[24h] offset -24h))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Daily Costs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Costs per AWS Account and Region",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(Publisher, RegionName) (max_over_time(aws_cost[24h] offset -24h))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}