apiVersion: v1	
kind: Service
metadata:
  name: aws-cost-exporter
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/name: aws-cost-exporter
  type: ClusterIP
